### ISSUE TITLE
Load offset/map offset are ignored

### ISSUE THREAD

**Issue by KarolS** [radareorg/cutter#524]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10 x64
| File format of the file you reverse (mandatory)      | Commodore PRG
| Architecture/bits of the file (mandatory)            | 6502 (8-bit)
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.4 / Using r2 2.5.0-105-gc79874941
| Show version information **full output** (See About Cutter) in a pastebin document (mandatory) | https://pastebin.com/K5V00mHt

### Expected behavior

When loading a PRG file with load offset 2 and map offset 0x801, it should be loaded as specified.

### Actual behavior

The file gets loaded with both offsets equal zero, which leads to all absolute addresses being wrong and flow analysis jumping randomly over the code, frequently in the middle of an instruction.

### Steps to reproduce the behavior 
- load the attached binary: [echo.zip](https://github.com/radareorg/cutter/files/2082085/echo.zip)
- set architecture to 6502
- set load offset to 2 and map offset to 0x801 (I tried various syntaxes: 0x801, 801, 0x00000801, $801)

### Additional screenshots

![2018-06-07 23_14_51-cutter](https://user-images.githubusercontent.com/1790750/41126892-589d2212-6aa9-11e8-8a40-9e23d765e2b4.png)

EDIT: for comparison, the same fragment in Regenerator 1.7, with the initial 12-byte BASIC block marked manually by me as non-executable data:

![obraz](https://user-images.githubusercontent.com/1790750/41129059-b56d1a72-6ab0-11e8-82f3-421e61c04b0c.png)

**Comment by xarkes** [comment]
Hi,
Just to clarify a bit, if I am not mistaken:
- Load Address (`-B`) is here to tell Cutter where the file header begins. In your case, it begins at 0x0, so it should remain empty (or 0).
- Map Address (`-m`) tells Cutter to shift your binary to a specific offset

In my case I often work with `-m` and I have no issues with that. Maybe there is a bug when modifying both fields, but I cannot reproduce it.

**Comment by xarkes** [comment]
Here is what I have when modifying Map Address only:
![2018-06-08-084358_1066x829_scrot](https://user-images.githubusercontent.com/10772605/41143024-22e5ccc4-6af8-11e8-8a41-9992502bf55c.png)
Which looks good to me.

**Comment by KarolS** [comment]
The first two bytes are not the part of the program, they are the file header, they should not be loaded. The byte at address 0x801 should be 0x0b.

Anyway, the CLI version of Radare2 works fine, it's the Cutter GUI that I have a problem with. This is what I'm doing:
![obraz](https://user-images.githubusercontent.com/1790750/41157597-9f76bee6-6b26-11e8-9261-2188a2ba33c2.png)

After a cursory glance at the source at the v1.4 tag , I can't find any piece of code that reads the `entry_loadOffset` and `entry_mapOffset` widgets. It looks like it will be fixed in 1.5? https://github.com/radareorg/cutter/commit/923a7e888c3600f94d6d317fe9d652af31618204

**Comment by xarkes** [comment]
Ah indeed. I thought that was fixed before, sorry about that. Yes you can download the latest build from here:
https://ci.appveyor.com/project/radare/cutter/branch/master/job/dnov3995y8aq2jog/artifacts
Let me know if that fixes it.

**Comment by KarolS** [comment]
Yes, in this newer version everything looks fine.
The -B option still doesn't do anything interesting, but loading with -m 0x7ff works good enough.
Maybe I'll submit one day a patch for Radare2 with proper PRG file support.
Thanks.
